DROP TABLE Invitation CASCADE CONSTRAINTS PURGE;

CREATE TABLE Invitation
  (
    TARGETPID   INTEGER NOT NULL,
    PID         INTEGER NOT NULL,
    LID         INTEGER NOT NULL,
    CONSTRAINT Invitation_Lunch_FK FOREIGN KEY ( LID ) REFERENCES Lunch ( LID ) ON DELETE CASCADE
  ) ;
ALTER TABLE Invitation ADD CONSTRAINT Invitation_PK PRIMARY KEY ( TARGETPID, PID, LID ) ;
ALTER TABLE Invitation ADD CONSTRAINT Invitation_Person_FK FOREIGN KEY ( PID ) REFERENCES Person ( PID ) ;
ALTER TABLE Invitation ADD CONSTRAINT Invitation_Target_Person_FK FOREIGN KEY ( TARGETPID ) REFERENCES Person ( PID ) ;

INSERT INTO Invitation (TARGETPID, PID, LID)
VALUES (3, 1, 1);
INSERT INTO Invitation (TARGETPID, PID, LID)
VALUES (4, 2, 2);

commit;

--delete from invitation;

SELECT * FROM INVITATION;


