package huzevka.lunchfriends.list;

public class HobbyList {

	public static final String[] HOBBIES_EN = new String[] {
			"Acting",
			"Aeromodeling",
			"Airbrushing",
			"Aircraft Spotting",
			"Airsofting",
			"Alcohol",
			"Algorithms/Programming",
			"Amateur Astronomy",
			"Amateur Radio",
			"American football",
			"Animals",
			"Animals/pets/dogs",
			"Aquarium (Freshwater & Saltwater)",
			"Archery",
			"Arts",
			"Astrology",
			"Astronomy",
			"Athletics",
			"Aviation",
			"Backgammon",
			"Badminton",
			"Baseball",
			"Base Jumping",
			"Basketball",
			"Beachcombing",
			"Beach/Sun tanning",
			"Beadwork",
			"Beatboxing",
			"Beauty",
			"Becoming A Child Advocate",
			"Bell Ringing",
			"Belly Dancing",
			"Bicycle Polo",
			"Bicycling",
			"Biology",
			"Birding",
			"Bird watching",
			"Blacksmithing",
			"Blogging",
			"BMX",
			"BoardGames",
			"Board Games",
			"Boating",
			"Bodybuilding",
			"Body Building",
			"Bonsai Tree",
			"Bookbinding",
			"Boomerangs",
			"Bowling",
			"Brewing Beer",
			"Bridge Building",
			"Bringing Food To The Disabled",
			"Building A House For Habitat For Humanity",
			"Building Dollhouses",
			"Butterfly Watching",
			"Button Collecting",
			"Cake Decorating",
			"Calligraphy",
			"Camping",
			"Candle Making",
			"Canoeing",
			"Card Games",
			"Car Racing",
			"Cars",
			"Cartooning",
			"Casino Gambling",
			"Cats",
			"Cave Diving",
			"Ceramics",
			"Cheerleading",
			"Chemistry",
			"Chess",
			"Church/church activities",
			"Cigar Smoking",
			"Climbing",
			"Cloud Watching",
			"Coin Collecting",
			"Collecting",
			"Collecting Antiques",
			"Collecting Artwork",
			"Collecting Hats",
			"Collecting Music Albums",
			"Collecting RPM Records",
			"Collecting Sports Cards",
			"Collecting Swords",
			"Collecting things",
			"Coloring",
			"Compose Music",
			"Computer activities",
			"Computers",
			"Computer science",
			"Conworlding",
			"Cooking",
			"Cosplay",
			"Crafts",
			"Crafts (unspecified)",
			"Crochet",
			"Crocheting",
			"Cross-Stitch",
			"Crossword Puzzles",
			"Cycling",
			"Dancing",
			"Darts",
			"Diecast Collectibles",
			"Digital Photography",
			"Dodgeball",
			"Dogs",
			"Dolls",
			"Dominoes",
			"Drawing",
			"Drugs",
			"Dumpster Diving",
			"Eating out",
			"Educational Courses",
			"Electronics",
			"Embroidery",
			"Entertaining",
			"Exercise (aerobics, weights)",
			"Falconry",
			"Fast cars",
			"Felting",
			"Fencing",
			"Fire Poi",
			"Fishing",
			"Floorball",
			"Floral Arrangements",
			"Fly Tying",
			"Food",
			"Football",
			"Football/soccer",
			"Four Wheeling",
			"Freshwater Aquariums",
			"Frisbee",
			"Frisbee Golf",
			"Games",
			"Gaming",
			"Garage Saleing",
			"Gardening",
			"Genealogy",
			"Geocaching",
			"Geography",
			"Geology",
			"Ghost Hunting",
			"Glowsticking",
			"Gnoming",
			"Going to movies",
			"Go Kart Racing",
			"Golf",
			"Grip Strength",
			"Guitar",
			"Gun Collecting",
			"Gunsmithing",
			"Gymnastics",
			"Gyotaku",
			"Hair styling",
			"Handwriting Analysis",
			"Hang gliding",
			"Healthy lifestyle",
			"Herping",
			"Hiking",
			"History",
			"Hockey",
			"Home Brewing",
			"Home pets",
			"Home Repair",
			"Home Theater",
			"Horse riding",
			"Horses",
			"Hot air ballooning",
			"Hula Hooping",
			"Hunting",
			"Iceskating",
			"Ice skating",
			"Illusion",
			"Impersonations",
			"Information technology",
			"Internet",
			"Inventing",
			"Jet Engines",
			"Jewelry Making",
			"Jigsaw Puzzles",
			"Jogging",
			"Juggling",
			"Jumping",
			"Jump Roping",
			"Kayaking",
			"Keep A Journal",
			"Kitchen Chemistry",
			"Kite Boarding",
			"Kites",
			"Knitting",
			"Knotting",
			"Lacrosse",
			"Languages",
			"Lasers",
			"Lawn Darts",
			"Learning A Foreign Language",
			"Learning An Instrument",
			"Learning To Pilot A Plane",
			"Learn to Play Poker",
			"Leathercrafting",
			"Legos",
			"Letterboxing",
			"Listening to music",
			"Literature",
			"Locksport",
			"Macramé",
			"Magic",
			"Making Model Cars",
			"Marksmanship",
			"Martial arts",
			"Matchstick Modeling",
			"Maths",
			"Medicine",
			"Meditation",
			"Metal Detecting",
			"Microscopy",
			"Mobile phones",
			"Modeling Ships",
			"Modelling",
			"Model Railroading",
			"Model Rockets",
			"Models",
			"Motorcycles",
			"Mountain Biking",
			"Mountain Climbing",
			"Music",
			"Musical Instruments",
			"Nail Art",
			"Nature",
			"Needlepoint",
			"Nutrition",
			"Origami",
			"Owning An Antique Car",
			"Paintball",
			"Painting",
			"Papermache",
			"Papermaking",
			"Parachuting",
			"Paragliding or Power Paragliding",
			"Parkour",
			"Parkour/freerunning",
			"People Watching",
			"Photography",
			"Physics",
			"Piano",
			"Pinochle",
			"Pipe Smoking",
			"Planking",
			"Playing music",
			"Playing team sports",
			"Poems",
			"Poker",
			"Pole Dancing",
			"Politics",
			"Pottery",
			"Powerboking",
			"Protesting",
			"Psychology",
			"Puppetry",
			"Pyrotechnics",
			"Quilting",
			"Racing Pigeons",
			"Rafting",
			"Railfans",
			"Rapping",
			"R/C Boats",
			"R/C Cars",
			"R/C Helicopters",
			"R/C Models",
			"R/C Planes",
			"Reading",
			"Reading books",
			"Reading To The Elderly",
			"Relaxing",
			"Renaissance Faire",
			"Renting movies",
			"Rescuing Abused Or Abandoned Animals",
			"Robotics",
			"Rock Balancing",
			"Rock Collecting",
			"Rockets",
			"Rocking AIDS Babies",
			"Roleplaying",
			"Roller skating",
			"Running",
			"Sailing",
			"Saltwater Aquariums",
			"Sand Castles",
			"Sciences",
			"Sci-fi/fantasy",
			"Scrapbooking",
			"Scuba Diving",
			"Self Defense",
			"Sewing",
			"Shark Fishing",
			"Shopping",
			"Singing",
			"Singing In Choir",
			"Skateboarding",
			"Skeet Shooting",
			"Sketching",
			"Skiing",
			"Sky Diving",
			"Slackline",
			"Slack Lining",
			"Sleeping",
			"Slingshots",
			"Slot Car Racing",
			"Snorkeling",
			"Snowboarding",
			"Soap Making",
			"Soccer",
			"Socializing with friends/neighbors",
			"Speed Cubing (rubix cube)",
			"Spelunkering",
			"Spending time with family/kids",
			"Sports",
			"Stamp Collecting",
			"Storm Chasing",
			"Storytelling",
			"String Figures",
			"Studying",
			"Surf Fishing",
			"Surfing",
			"Survival",
			"Swimming",
			"Tatting",
			"Taxidermy",
			"Tea Tasting",
			"Technology",
			"Tennis",
			"Tesla Coils",
			"Tetris",
			"Textiles",
			"Texting",
			"Theatre",
			"Tombstone Rubbing",
			"Tool Collecting",
			"Toy Collecting",
			"Train Collecting",
			"Train Spotting",
			"Traveling",
			"Travelling",
			"Treasure Hunting",
			"Trekkie",
			"Tutoring Children",
			"TV watching",
			"Ultimate Frisbee",
			"Urban Exploration",
			"Video Games",
			"Violin",
			"Volunteer",
			"Walking",
			"Warhammer",
			"Watching movies",
			"Watching sporting events",
			"Weather Watcher",
			"Weightlifting",
			"Windsurfing",
			"Wine Making",
			"Wingsuit Flying",
			"Women",
			"Woodworking",
			"Working In A Food Pantry",
			"Working on cars",
			"World Record Breaking",
			"Wrestling",
			"Writing",
			"Writing Music",
			"Writing Songs",
			"Yoga",
			"YoYo",
			"Ziplining",
			"Zumba"
	};

	public static final String[] HOBBIES_CS = new String[] {
			"Airsoft",
			"Akvaristika",
			"Algoritmy/Programování",
			"Alkohol",
			"Amatérská astronomie",
			"Amatérské rádio",
			"Americký fotbal",
			"Aranžování květin",
			"Astrologie",
			"Astronomie",
			"Atletika",
			"Auta",
			"Badminton",
			"Baseball",
			"Base Jumping",
			"Basketbal",
			"Básně",
			"Beatboxing",
			"Běh",
			"Biologie",
			"Blogování",
			"BMX",
			"Bodybuilding",
			"Bojová umění",
			"Bonsai stromy",
			"Břišní tanec",
			"Bruslení na ledě",
			"Cestování",
			"Chemie",
			"Chůze",
			"Církevní činnost",
			"Cosplay",
			"Čtení knih",
			"Cvičení",
			"Cyklistika",
			"Degustace čaje",
			"Dějiny",
			"Dekorování dortů",
			"Detekce kovů",
			"Digitální fotografie",
			"Divadlo",
			"Dobrovolnictví",
			"Domácí vaření piva",
			"Domácí zvířata",
			"Domino",
			"Doučování dětí",
			"Draci",
			"Dřevěné modely",
			"Drhání",
			"Elektronika",
			"Filmy",
			"Florbal",
			"Fotbal/Futsal",
			"Fotografování",
			"Freerunning",
			"Frisbee",
			"Frisbee Golf",
			"Frivolitky",
			"Fyzika",
			"Garážové výprodeje",
			"Genealogie",
			"Geocaching",
			"Geologie",
			"Golf",
			"Grafologie",
			"Gymnastika",
			"Háčkování",
			"Házení bumerangem",
			"Herectví",
			"Hledání pokladů",
			"Hokej",
			"Horolezectví",
			"Horská cyklistika",
			"Housle",
			"Hrady z písku",
			"Hraní her",
			"Hraní týmových sportů",
			"Hrnčířství",
			"Hry",
			"Hudba",
			"Hudební nástroje",
			"Hula Hooping",
			"Iluze/Magie",
			"Informační technologie",
			"Internet",
			"Jazyky",
			"Jídlo",
			"Jízda na kole",
			"Jízda na koni",
			"Jóga",
			"Jogging",
			"Kajakování",
			"Kaligrafie",
			"Kanoistika",
			"Karetní hry",
			"Kempování",
			"Keramika",
			"Kino",
			"Kite Boarding",
			"Klavír",
			"Kočky",
			"Kolečkové brusle",
			"Koně",
			"Kouření vodní dýmky",
			"Kouzla",
			"Kovářství",
			"Krása",
			"Kreslení",
			"Křížovky",
			"Kulturistika",
			"Kutilství",
			"Kuželky",
			"Kytara",
			"Lacrosse",
			"Lámání světových rekordů",
			"Lego",
			"Létající talíř",
			"Létání balónem",
			"Létání s wingsuit",
			"Letecké modelářství",
			"Letecké motory",
			"Letectví",
			"Lezení",
			"Literatura",
			"Lodě",
			"Loutkářství",
			"Lov",
			"Lukostřelba",
			"Lyžování",
			"Malování",
			"Matematika",
			"Medicína",
			"Mikroskopie",
			"Mobilní telefony",
			"Modelování",
			"Modelování lodí",
			"Modelování vláčků",
			"Modelové rakety",
			"Modely R/C",
			"Mořská akvária",
			"Motocykly",
			"Motokáry",
			"Nakupování",
			"Navlékání korálků",
			"Nehtová móda",
			"Ochotnictví",
			"Opalování",
			"Origami",
			"Paintball",
			"Panenky",
			"Papírmaš",
			"Paragliding",
			"Parašutismus",
			"Parkour",
			"Pilotování letadla",
			"Plachtění",
			"Plavání",
			"Pletení",
			"Plstění",
			"Počítače",
			"Počítačová věda",
			"Počítačové činnosti",
			"Poker",
			"Politika",
			"Poslouchání hudby",
			"Potápění",
			"Pozorování ptáků",
			"Práce na autech",
			"Práce na zahradě",
			"Praky",
			"Přehrávání hudby",
			"Přežití",
			"Příroda",
			"Protestování",
			"Psaní",
			"Psaní hudby",
			"Psaní písní",
			"Psát si deník",
			"Psi",
			"Psychologie",
			"Puzzle",
			"Pyrotechnika",
			"Rafting",
			"Rakety",
			"Rap",
			"R/C auta",
			"R/C čluny",
			"R/C letadla",
			"R/C vrtulníky",
			"Relaxování",
			"Řemesla",
			"Robotika",
			"Rozjímání",
			"Roztleskávání",
			"Rubikova kostka",
			"Rybolov",
			"Rychlá auta",
			"Šachy",
			"Sběr motýlů",
			"Sbírání aut",
			"Sbírání hraček",
			"Sbírání hudebních alb",
			"Sbírání kamenů",
			"Sbírání klobouků",
			"Sbírání mečů",
			"Sbírání mincí",
			"Sbírání nástrojů",
			"Sbírání sport. karet",
			"Sbírání starožitností",
			"Sbírání uměleckých děl",
			"Sbírání věcí",
			"Sbírání zbraní",
			"Sbírání známek",
			"Sci-fi/fantasy",
			"Sebeobrana",
			"Šipky",
			"Šití",
			"Skákání",
			"Skateboarding",
			"Skládání hudby",
			"Sky diving",
			"Slackline",
			"Sladkovodní akvária",
			"Sledování filmů",
			"Sledování sportů",
			"Sledování televize",
			"Šnorchlování",
			"Snowboarding",
			"Sokolnictví",
			"Spaní",
			"Sportování",
			"Stolní hry",
			"Storm chasing",
			"Střelectví",
			"Studium",
			"Surfování",
			"Švihadlo",
			"Tanec",
			"Tanec u tyče",
			"Technika",
			"Tenis",
			"Tetris",
			"Trávit čas s rodinou/dětmi",
			"Turistika",
			"Učení cizího jazyka",
			"Umění",
			"Úprava vlasů",
			"Vaření",
			"Vaření piva",
			"Vázání knih",
			"Vědy",
			"Videohry",
			"Vína",
			"Vlastnit starožitná auta",
			"Vrhcáby",
			"Vybíjená",
			"Výkresy",
			"Vynalézání",
			"Vyprávění příhod",
			"Výroba modelových vozů",
			"Výroba papíru",
			"Výroba šperků",
			"Výroba svíček",
			"Vyšívání",
			"Výživa",
			"Vzdělávací kurzy",
			"Vzpírání",
			"YoYo",
			"Zachraňování zvířat",
			"Zahradní šipky",
			"Zápas",
			"Závodění s autíčky",
			"Závodní holubi",
			"Závody aut",
			"Zdravý životní styl",
			"Zeměpis",
			"Ženy",
			"Žonglování",
			"Zpěv",
			"Zpěv ve sboru",
			"Zpracování dřeva",
			"Zumba",
			"Zvířata"
	};

}
